import random

# Define a function for wild encoutners.
def encounterFunction():
    # Set global variables that can be called outside of the function.
    global wildPokemon

    encounterValue = random.randint(1,100)
    shinyValue = random.randint(1,8192)


    # Return a value for wildPokemon based on the int generated by encounterValue.
    if encounterValue in range (1,30):
        wildPokemon = "snubull"
    elif encounterValue in range  (31,60):
        wildPokemon = "rattata"
    elif encounterValue in range  (61,80):
        wildPokemon = "pidgey"
    elif encounterValue in range  (81,90):
        wildPokemon = "abra"
    elif encounterValue in range  (91,95):
        wildPokemon = "jigglupyff"
    elif encounterValue in range  (96,100):
        wildPokemon = "ditto"

    # Add the shiny property if the shinyValue matches the static int 450.
    if shinyValue == (450):
        print("shiny " + wildPokemon)
    else:
        print(wildPokemon)
    
    return

# Simulate taking 5,678 steps in tall grass.
steps = 0
while (steps <= 5678):
    encounterFunction()
    steps += 1
